разметка главной страницы
htmlacademy-htmlcss/1661109-nerds-30 pull request #2
Opened 2021-01-25 00:15 UTC by oaroz

разметка, вопросы, варианты решения в комментариях

2021-01-25 15:54 UTC, gonch0 requested changes

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +                <!--изображение декоративное будет в стилях-->
Не соглашусь.
Элементы секции (веб-сайты, приложения, презентации) - товары нашего ИМ Нёрдс, а значит несут смысл для пользователя (см учебника [шаг 5 учебника](https://up.htmlacademy.ru/htmlcss/30/book/1.5))

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +          <!--есть ли тег "заголовок списка"? или только так? либо лучше h4 или списком?-->
Заголовка списка нет, но есть просто заголовок h1-h6

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +           <figcaption>Выполняем заказы на разработку:</figcaption>
figure здесь лишний. Внутри нет никакого демонстрационного контента наподобие диаграмм, изображений.
Вместо figcaption лучше использовать заголовок.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +          <p>Мы — маленькая, но гордая<br>дизайн-студия из Краснодара.</p>
Скрытый h3 здесь лишний, а `Мы — маленькая, но гордая студия`  - и есть заголовок этой секции.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +               <!--%в стилях потом выделять? можно обойтисьб без <span>?-->
Без span не обойтись. Но вместо span лучше использовать [sup](https://htmlacademy.ru/courses/301/run/14)

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +          <figure>
Здесь figure также лишний.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +             <dl>
`dl` служит контейнером для списка пар терминов. 
Больше подходит `ul`

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +      <h2>Контакатная информация</h2>
Контакатная -> Контактная

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +       <img src="https://via.placeholder.com/1440x416" alt="На карте города">
Можно не оборачивать, но почему бы и нет? Этот блок вполне себе полноценная секция "Карта" (со скрытым заголовком)
Как накладывать пин - разбираем позже.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +        <figure>
figure лишний

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +        <h3>Адрес</h3>
Этот попап с адресом относится к секции с Картой. Как визуально, так и по смыслу.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +          <!--как читалка воспризведет немецкое (?) слово? нужно ли переключать язык локально, на эту фразу? как?-->
Слово не немецкое, просто в слове Nerds e заменили на ё. 
Заморачиваться в этой ситуации за верное воспроизведение фразы уже перебор)

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +            наверное, с submit неправильно (инф-я так вроде ОТСЫЛАЕТСЯ, кстати,где пишется путь, куда, найти...)-->
Верно, информация никуда не отсылается, эта кнопка нужна для открытия модального окна.
Стало быть, не type="submit", а другой)

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +        <!--иконки контентные или декоративные, или вообще их к тексту-ссылке потом стилем привязать?-->
Контентные.

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +      <section>
Лишняя обёртка `section`. Можно оставить просто два `p` рядом

2021-01-25 15:54 UTC, gonch0 commented on index.html
> +        <!--если сделать ссылки в строку, между ними остется подчеркивание - как почему???... втавка табуляции никак не вляет, что с ней, что без нее - вид одинаковый-->
Потому что как ссылки `a`, так и `span` - [строчные элементы](https://htmlacademy.ru/courses/44/run/2).

span лишний, сейчас мы заботимся о смысловой разметке, о внешнем виде (стилях) позаботимся чуть позже, расставим всё как надо.

2021-01-30 21:29 UTC, oaroz commented on index.html
> +    <title>Учебный проект «Нёдс»</title>
ок

2021-01-30 21:31 UTC, oaroz commented on index.html
> +        <!--если сделать ссылки в строку, между ними остется подчеркивание - как почему???... втавка табуляции никак не вляет, что с ней, что без нее - вид одинаковый-->
ок

2021-01-30 21:33 UTC, oaroz commented on index.html
> +      <section>
ок

2021-01-30 21:48 UTC, oaroz commented on index.html
> +            наверное, с submit неправильно (инф-я так вроде ОТСЫЛАЕТСЯ, кстати,где пишется путь, куда, найти...)-->
ок

2021-01-30 21:49 UTC, oaroz commented on index.html
> +          <!--как читалка воспризведет немецкое (?) слово? нужно ли переключать язык локально, на эту фразу? как?-->
ок

2021-01-30 21:53 UTC, oaroz commented on index.html
> +        <!--иконки контентные или декоративные, или вообще их к тексту-ссылке потом стилем привязать?-->
ок

2021-01-30 21:56 UTC, oaroz commented on index.html
> +        <figure>
jr

2021-01-30 22:01 UTC, oaroz commented on index.html
> +        <h3>Адрес</h3>
ок

2021-01-30 22:02 UTC, oaroz commented on index.html
> +       <img src="https://via.placeholder.com/1440x416" alt="На карте города">
ок

2021-01-30 22:02 UTC, oaroz commented on index.html
> +      <h2>Контакатная информация</h2>
ок

2021-01-30 22:07 UTC, oaroz commented on index.html
> +               <!--%в стилях потом выделять? можно обойтисьб без <span>?-->
ок

2021-01-30 22:12 UTC, oaroz commented on index.html
> +             <dl>
ок

2021-01-30 22:21 UTC, oaroz commented on index.html
> +           <figcaption>Выполняем заказы на разработку:</figcaption>
ок

2021-01-30 22:22 UTC, oaroz commented on index.html
> +          <!--есть ли тег "заголовок списка"? или только так? либо лучше h4 или списком?-->
ок

2021-01-30 22:22 UTC, oaroz commented on index.html
> +          <p>Мы — маленькая, но гордая<br>дизайн-студия из Краснодара.</p>
ок

2021-01-30 22:32 UTC, oaroz commented on index.html
> +                <!--изображение декоративное будет в стилях-->
ок

2021-01-30 22:34 UTC, oaroz commented on index.html
> +              <!--можно ли этот блок без обертки в section давать, но как пункт списка?-->
ок

2021-01-30 22:35 UTC, oaroz commented on index.html
> +         либо ВМЕСТО ul-списк сделать dl? целесообразнее (правда, визуально пока все слипается):
ок

2021-01-30 22:35 UTC, oaroz commented on index.html
> +          либо вложить в список пары <dl>? не быстрее будет потом описать стили для dt и dd на всю секцию сразу, чем на каждую пару <p>? правда, тегов больше, тоже многословно...
ок

2021-01-30 22:37 UTC, oaroz commented on index.html
> +            или это не логично и не нужно? по смыслу это ссылка. а вид кнопки - изыск дизайна, который подгоняется стилем?-->
ок

2021-01-30 22:37 UTC, oaroz commented on index.html
> +            <p>Математически выверенный дизайн<br>для вашего сайта или мобильного приложения.</p>
ок

2021-01-30 22:42 UTC, oaroz commented on index.html
> +            <p>Долго, дорого, скрупулезно</p>
а в статье учебника именно об этом тексте говjрится что это не заголовок. Хотя как заголовок тоже расценить с редакторской точки зрения....

2021-01-30 22:42 UTC, oaroz commented on index.html
> +            <!--изображение,скорее,декоративное,тогда дальнейшее не нужно?<img src="img/slide1.png" widht="760"heigt="431"alt="Коллаж из смартфонов">-->
ок

2021-01-30 22:50 UTC, oaroz commented on index.html
> +            как реализовать сам слайдер - (=переключение между списками?). по какому элементу переход - по точкам: по щелчку мыши?-->
ок. но как связать кнопку соответсвующим слайдом?-->
      <!-- есть смысл вложить кажду кнопку в список совего слайда?  
      или при выклюяении слайда и кнопка будет тогда пропадать,
      если она под ним?

2021-01-30 22:51 UTC, oaroz commented on index.html
> +            <!--блока слайда=пункту списка?
ок

2021-01-30 22:52 UTC, oaroz commented on index.html
> +        <ul>
ок

2021-01-31 08:02 UTC, merged