Стилизация главной страницы
htmlacademy-htmlcss/1661109-nerds-30 pull request #7
Opened 2021-02-21 23:20 UTC by oaroz

Стилизация главной страницы

2021-02-22 15:06 UTC, gonch0 requested changes
В рамках этого ДЗ у нас только **главная**.
Чтобы не делать двойную работу, давай сначала разберемся с ней, а уже потом с Каталогом.

В целом - пересмотри лекцию 4 и пока что отложи вопросы не по теме (декоративные элементы, контейнеры, размеры кнопок), сконцентируйся на задании к этому разделу.

2021-02-22 15:06 UTC, gonch0 commented on index.html
> +          <p><a class="button service-button service-pres-button" href="blank.html">Заказать</a></p>
Обёртка p лишняя (здесь и в аналогичных местах)

2021-02-22 15:06 UTC, gonch0 commented on css/style.css
> +/* это подключение для тренировки и проверки правильности написания. в html шрифты подключены с google.fonts */
Хорошо, но позже (до момента сдачи проекта) этот код надо удалить.

2021-02-23 10:21 UTC, oaroz commented on index.html
> +  <!-- избегаем классов по тегам?? или убрать этот класс и делать по тегу body? -->
ок

2021-02-23 10:22 UTC, oaroz commented on index.html
> +      <!-- зачем эти классы. они не излишни? -->
ок

2021-02-23 10:41 UTC, oaroz commented on index.html
> +        <!-- в нашем случае нужно ли задавать класс постоянному везде логотипу? -->
ЗАЧЕМ ПРАВИЛО? ведь мы не можем упавлять картинкой (см. ниже)?? и почему логотип вначале красится, а в партнерах нет??

2021-02-23 10:41 UTC, oaroz commented on index.html
> +      <!-- класс ссылке или картинке?? по клику ихмениь краоинк на серую или цвет картинки в векторе в свг -->
все дерево описывать вложенное... разве нет?

2021-02-23 10:43 UTC, oaroz commented on index.html
> +      <!-- класс ссылке или картинке?? по клику ихмениь краоинк на серую или цвет картинки в векторе в свг -->
тут вопрос об управлении и свойстве илл.  а ее можно достать прост по тегу, вложенному в стиль, и не делать отдельный стиль наверное...

2021-02-23 10:46 UTC, oaroz commented on index.html
> +        <!-- в нашем случае нужно ли задавать класс постоянному везде логотипу? -->
можно ли вложенность не прямую, а через родителя делать? .main-header img

2021-02-23 10:57 UTC, oaroz commented on index.html
> +        <!-- нужен ли класс на пункты-ссылки? class="nav-href" -->
ок

2021-02-23 11:00 UTC, oaroz commented on index.html
> +        <!-- либо завернуть кнопки в div и div-у назначить этот класс единожды?
ок

2021-02-23 11:12 UTC, oaroz commented on index.html
> +    <!-- скрыть h1 _ А МОЖЕТ ЕГО ВООБЩЕ УБРАТЬ??-->
ок

2021-02-23 11:14 UTC, oaroz commented on index.html
> +    <!-- скрыть h1 _ А МОЖЕТ ЕГО ВООБЩЕ УБРАТЬ??-->
но зачем там даны ширина, дина. поля 

.visually-hidden {
  position: absolute;
  clip: rect(0 0 0 0);
  width: 1px;
  height: 1px;
  margin: -1px;
  …
}

2021-02-23 11:23 UTC, oaroz commented on index.html
> +        относить ли эти кнопки к общему общему классу кнопок?они вообще другие тут... -->
ок

2021-02-23 11:51 UTC, oaroz commented on index.html
> +            <!-- class="page-title" из catalog плюс выключка влево. какой класс тут целесообразнее? advantage-title - потомомк page-title-->
убрала вообще, переназначила через вложенность

2021-02-23 11:51 UTC, oaroz commented on index.html
> +            <!-- наверное не надо класс на текст, елси он как раз body-text тут -->
добавлю позже, когда буду позионировать?

2021-02-23 11:52 UTC, oaroz commented on index.html
> +            <!-- наверное не надо класс на текст, елси он как раз body-text тут -->
или через вложенность класса advantage-item сделаю

2021-02-23 11:58 UTC, oaroz commented on index.html
> +          <h3 class="servise-title">Приложения</h3>
убрала,переназначила через вложенность

2021-02-23 11:58 UTC, oaroz commented on index.html
> +            <!-- красные палки в виде буллитов? ? -->
понимаю, но как именно? позже?

2021-02-23 12:11 UTC, oaroz commented on index.html
> +            <!-- убрать класс about-item? это ведь body-text? отбивки между строками чем увеличивать -->
ок

2021-02-23 12:22 UTC, oaroz commented on index.html
> +          <!-- не хочется делать еще один класс, можно сделать класс center или переменную с центральной выключкой и все?  и его можно исполоьзовать будет для центровки любого элемента... тут разница
ок, переназначила все

2021-02-23 12:46 UTC, oaroz commented on index.html
> +        <!-- это about-list-header-center плюс другой цвет и интерлиньяж...-->
ок

2021-02-23 12:47 UTC, oaroz commented on index.html
> +        <!-- это body-text, отличающийся только цветом... -->
ок

2021-02-23 12:53 UTC, oaroz commented on index.html
>      </section>
не нашла (

2021-02-23 12:54 UTC, oaroz commented on index.html
> +        <li>
забыла ( ок

2021-02-23 13:01 UTC, oaroz commented on index.html
> +    <!-- декоративные иконки соцсетей вместо названий - как убрать названия?-->
а если вложить в ссылку img или декоративную картинку, а текст в альт

2021-02-23 13:04 UTC, oaroz commented on blank.html
> +        <p class="about-list-header-center contacts-header">NЁRDS DESIGN STUDIO</p>
ок

2021-02-23 13:05 UTC, oaroz commented on catalog.html
> +    <!--заголовок иденетичен h3 class="advantage-header" c index... только ц ентральная выключка... может там и тут сделать h1 им обоим? -->
а как же по требование по тегу не делать классы?

2021-02-23 13:10 UTC, oaroz commented on blank.html
> +<body class="page-body">
ок

2021-02-23 13:10 UTC, oaroz commented on blank.html
> +        <!-- в нашем случае нужно ли задавать класс постоянному везде логотипу? -->
поменяю после готовности индекса

2021-02-23 13:18 UTC, oaroz commented on css/style.css
> +  --button-social: #E1E1E1;
да, но не понимаю, как прикрутить прозрачность, она влияет на все элементы, а надо только тень или только текст. в кнопке по нажатию надо и цвет теста со свей прозрачностью сделать, и тень на бэкграунде кнопки со своей прозрачностью. как это сделать не rgba, а opacity?

2021-02-23 13:19 UTC, oaroz commented on css/style.css
> +    color: var(--accent);
ок

2021-02-23 13:21 UTC, oaroz commented on css/style.css
> +
вот как раз тот случай, когда сработало состояние цвета на свг. а в блоке партнеров тот же принцип не срабатывает.

2021-02-23 13:21 UTC, oaroz commented on css/style.css
> +
плюс разобраться с добавлением прозрачности

2021-02-23 13:34 UTC, oaroz commented on css/style.css
> +     background: --basic-light;
ок

2021-02-23 13:39 UTC, oaroz commented on css/style.css
> +только один лого векторый, другим надо иначе делать hover и focus - другие классы? */
но это растровый картинки, как мы можем внутри них командовать цветом. только прозрачностью разве что. 

.partners-item img или .partners-item a - управление картинкой невозможно? плюс через родителя перескок допустим?

2021-02-23 14:00 UTC, oaroz commented on css/style.css
> +/* почему не срабатывает смена цвета? в лого сайта срабатывало */
к чему цеплять прозрачность???

2021-02-23 14:01 UTC, oaroz commented on css/style.css
> +/* свойство прозрачности бы к цветам приделывать, чтобы не плодить кучу цветов из-за нее. не пойму, как реализовать
вот в этом и вся проблема! куда ее цеплять, прозрачность

2021-02-23 14:09 UTC, oaroz commented on css/style.css
> +  color: var(--basic-dark);
да. а как тогда поменять прозрачность или цвет логотипам? см выше. в самом свг?

а управление там шло от вышестоящего класса поп всем ссылкам  навигации. но ведь тоже сработало почему-то...

2021-02-23 14:09 UTC, oaroz commented on css/style.css
> +/* как центровать? */
ок

2021-02-23 14:15 UTC, oaroz commented on css/style.css
> +  var (--basic-dark);
ок

2021-02-23 14:16 UTC, oaroz commented on css/style.css
> +  height: 50px;
потом разобраться. тогда все кнопки зависят от ширины текста. или все-таки подгонять под макет?

2021-02-23 14:16 UTC, oaroz commented on css/style.css
> +  height: 50px;
а если две рядом кнопки, а текст разной длины? кнопки должны же быть одинаковые... см. в след. лекции...

2021-02-23 14:17 UTC, oaroz commented on css/style.css
> +/*кнопка после нажатия залипает на состоянии фокуса. приходит в себя только по клику на пустое место. как сделать по умолчанию?  */
понятно. но тогда нам фокус наверное и не нужен? или фокус=актив делать?

2021-02-23 14:18 UTC, oaroz commented on css/style.css
> +}
ок

2021-02-23 14:18 UTC, oaroz commented on css/style.css
> +}
ок

2021-02-23 14:20 UTC, oaroz commented on css/style.css
> +    height: 50px; как изменить размер??? может с помощью полей по ширине текста?*/
разобраться с тренажером и отступами позже.

2021-02-23 14:20 UTC, oaroz commented on css/style.css
> +  var(--basic-dark);
ок

2021-02-23 14:21 UTC, oaroz commented on css/style.css
> +}
фокус на кнопку вообще нужен? меняю его на актив... или сделать оба, но одинаковыми?

2021-02-23 14:22 UTC, oaroz commented on css/style.css
> +}
перепутала я фокус с нажатием (

2021-02-23 14:22 UTC, oaroz commented on index.html
> +          <p><a class="button service-button service-pres-button" href="blank.html">Заказать</a></p>
ок

2021-02-23 14:22 UTC, oaroz commented on css/style.css
> +/* это подключение для тренировки и проверки правильности написания. в html шрифты подключены с google.fonts */
ок, проверить еще раз поправленное

2021-02-23 14:35 UTC, oaroz commented on css/style.css
> +  color: var(--basic-dark);
не могу найти подробностей про devtools - что там отключать где. и посему там есть зачеркнутые строки и в стилях переменных по цвету? они избыточны?

2021-02-24 20:27 UTC, merged